replicaCount: 1

image:
  repository: "630019796862.dkr.ecr.eu-central-1.amazonaws.com/ravid-retail-store-checkout"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 256Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
